<?php

/**
 * @file
 * The install part of the module.
 */

/**
 * Implements hook_install().
 */
function exif_install() {
  config_set('exif.settings', 'exif_update', TRUE);
  // Dynamically generated variable data was detected on the following lines.
}

/**
 * Implements hook_install().
 */
function exif_uninstall() {
  config_clear('exif.settings', 'exif_update');
}

/**
 * Implements hook_requirements().
 */
function exif_requirements($phase) {
  $t = get_t();
  $requirements = array();
  if ($phase == 'runtime' || $phase == 'install') {
    if (!function_exists('exif_read_data')) {
      $requirements['exif_read_data'] = array(
        'title' => $t('EXIF library is not available'),
        'description' => $t('The Function exif_read_data is not available on the system. Please ensure the PHP module named EXIF has been installed.'),
        'value' => $t('EXIF library is not available'),
        'severity' => REQUIREMENT_ERROR,
      );
    }
    if (!function_exists('iptcparse')) {
      $requirements['iptcparse'] = array(
        'title' => $t('IPTC library is not available'),
        'description' => $t('The Function iptcparse is not available on the system. Please ensure the PHP module named GD has been installed.'),
        'value' => $t('GD library is not available'),
        'severity' => REQUIREMENT_ERROR,
      );
    }
    if (!function_exists('GetImageSize')) {
      $requirements['GetImageSize'] = array(
        'title' => $t('Image library is not available'),
        'description' => $t('The Function GetImageSize is not available on the system. Please ensure the PHP module named GD has been installed.'),
        'value' => $t('GD library is not available'),
        'severity' => REQUIREMENT_ERROR,
      );
    }
    if (!function_exists('mb_convert_encoding')) {
      $requirements['mb_convert_encoding'] = array(
        'title' => $t('Multibyte library is not available'),
        'description' => $t('The Function mb_convert_encoding is not available on the system. Please ensure the PHP module named php-mbstring has been installed.'),
        'value' => $t('php-mbstring library is not available'),
        'severity' => REQUIREMENT_ERROR,
      );
    }
  }
  return $requirements;
}

/**
 * Migrate exif variables to config.
 */
function exif_update_1000() {
  $config = config('exif.settings');
  $config->set('exif_granularity', update_variable_get('exif_granularity', '0'));
  $config->set('exif_nodetypes', update_variable_get('exif_nodetypes', array()));
  $config->set('exif_mediatypes', update_variable_get('exif_mediatypes', array()));
  $config->set('exif_update', update_variable_get('exif_update', TRUE));
  $config->set('exif_extraction_solution', update_variable_get('exif_extraction_solution', 'php_extensions'));
  $config->set('exif_exiftool_location', update_variable_get('exif_exiftool_location', 'exiftool'));
  $config->set('exif_empty_values', update_variable_get('exif_empty_values', TRUE));
  $config->set('exif_vocabulary', update_variable_get('exif_vocabulary', array()));
  $config->set('date_format_exif', update_variable_get('date_format_exif', 'Y-m-d\TH:i:s'));
  $config->save();

  update_variable_del('exif_granularity');
  update_variable_del('exif_nodetypes');
  update_variable_del('exif_mediatypes');
  update_variable_del('exif_update');
  update_variable_del('exif_extraction_solution');
  update_variable_del('exif_exiftool_location');
  update_variable_del('exif_empty_values');
  update_variable_del('exif_vocabulary');
  update_variable_del('date_format_exif');
}
